# Generated by Django 5.1.5 on 2025-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_to_system',
            field=models.BooleanField(default=False),
        ),
    ]
