# Generated by Django 5.1.5 on 2025-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_access_to_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_to_system',
            field=models.BooleanField(default=False, verbose_name='Access to System'),
        ),
    ]
