# Generated by Django 4.2.23 on 2025-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_access_to_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_account',
            field=models.BooleanField(default=False, verbose_name='Adminstrative Account'),
        ),
    ]
