# Generated by Django 4.2.23 on 2025-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_admin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_account',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_to_system',
            field=models.BooleanField(default=True, verbose_name='Access to System'),
        ),
    ]
