# Generated by Django 4.2.23 on 2025-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Uncheck this box to deactivate user. They will no longer be able to log in.', verbose_name='active'),
        ),
    ]
