# Generated by Django 4.2.23 on 2025-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(max_length=150)),
                ('first_name', models.TextField(max_length=150)),
                ('dob', models.DateField()),
                ('street_address', models.TextField(max_length=150)),
                ('street_address_2', models.TextField(max_length=150)),
                ('city', models.TextField(max_length=150)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
                ('mailing_same', models.BooleanField(default=False)),
                ('mail_street_address', models.TextField(max_length=150)),
                ('mail_street_address_2', models.TextField(max_length=150)),
                ('mail_city', models.TextField(max_length=150)),
                ('mail_state', models.CharField(max_length=2)),
                ('mail_zip', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('phone_main', models.CharField(max_length=20)),
                ('phone_main_type', models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='Home', max_length=7)),
                ('phone_secondary', models.CharField(max_length=20)),
                ('phone_secondary_type', models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='Home', max_length=7)),
                ('cg_last_name', models.TextField(max_length=150)),
                ('cg_first_name', models.TextField(max_length=150)),
                ('cg_email', models.CharField(max_length=150)),
                ('cg_phone_main', models.CharField(max_length=20)),
                ('cg_notes', models.TextField()),
            ],
        ),
    ]
