# Generated by Django 4.2.23 on 2025-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cg_first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_address_2',
            field=models.CharField(max_length=150),
        ),
    ]
