# Generated by Django 4.2.23 on 2025-08-11 14:36

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_cg_first_name_alter_client_cg_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-11 09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_email',
            field=models.EmailField(max_length=254, verbose_name='Care Giver Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_first_name',
            field=models.CharField(max_length=150, verbose_name='Care Giver First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_last_name',
            field=models.CharField(max_length=150, verbose_name='Care Giver Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_notes',
            field=models.TextField(verbose_name='Care Giver Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_phone_main',
            field=models.CharField(max_length=20, verbose_name='Care Giver Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_street_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_street_address_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mailing_same',
            field=models.BooleanField(default=False, verbose_name='Mailing same as home'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
