# Generated by Django 4.2.23 on 2025-08-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_client_created_at_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Care Giver Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Care Giver First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Care Giver Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_notes',
            field=models.TextField(blank=True, verbose_name='Care Giver Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cg_phone_main',
            field=models.CharField(blank=True, max_length=20, verbose_name='Care Giver Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_state',
            field=localflavor.us.models.USStateField(blank=True, default='RI', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_street_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_street_address_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail_zip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=localflavor.us.models.USStateField(default='RI', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
