# Generated by Django 4.2.23 on 2025-08-12 18:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_created_by_client_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_main',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_secondary',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
