# Generated by Django 4.2.23 on 2025-08-17 17:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_phone_secondary_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_contact_name', models.CharField(max_length=50)),
                ('add_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('add_contact_phone_type', models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='Home', max_length=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_date', models.DateField()),
                ('goal_name', models.CharField(max_length=30)),
                ('goal_type', models.CharField(choices=[('Measurable', 'Measurable'), ('Subjective', 'Subjective'), ('Mandated', 'Mandated')], default='Measurable', max_length=25)),
                ('goal_tack_type', models.CharField(choices=[('YN', 'Yes/No'), ('Progress', 'Progress'), ('None', 'None')], default='Progress', max_length=25)),
                ('goal_time_spent', models.IntegerField()),
                ('goal_status', models.CharField(choices=[('Open', 'Open'), ('Achieved', 'Achieved'), ('Archived', 'Archived')], default='Open', max_length=25)),
                ('goal_target_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='GoalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_update_date', models.DateField()),
                ('g_status_update', models.CharField(choices=[('Evaluated', 'Evaluated'), ('Achieved', 'Achieved')], default='Evaluated', max_length=30)),
                ('g_status_staff_time', models.IntegerField()),
                ('g_status_progress_level', models.IntegerField(blank=True, choices=[(1, 'Not Started'), (2, 'No Improvement'), (3, 'Slight Improvement'), (4, 'Close to Goal'), (5, 'Achieved')], null=True)),
                ('g_status_notes', models.TextField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_status_record', to='client.goal')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
