# Generated by Django 4.2.23 on 2025-08-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0007_addcontacts_goal_goalupdate_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonTopicsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_topics', models.CharField(max_length=250)),
                ('reason_topic_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('action_type', models.CharField(choices=[('Phone', 'Phone Call'), ('Virtual', 'Virtual Meetng'), ('In_Person', 'In Person'), ('Office_Visit', 'Office Visit'), ('Email', 'Email Exchange'), ('Text', 'Text Message'), ('TeamViewer', 'TeamViewer Consult'), ('HW/SW In', 'Hardware / Software Delieverd'), ('HW/SW Out', 'Hardware / Software Pick-Up')], default='Phone', max_length=30)),
                ('action_init_by', models.CharField(choices=[('Client', 'Client'), ('Caregiver', 'Caregiver'), ('SHARE', 'SHARE'), ('3rd_Party', '3rd Party')], default='Client', max_length=30)),
                ('action_outcome', models.CharField(choices=[('Successful', 'Successful'), ('Followup', 'Requires Follow-Up')], default='Successful', max_length=30)),
                ('action_notes', models.TextField(blank=True, null=True)),
                ('action_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_for_client', to='client.client')),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
