# Generated by Django 4.2.23 on 2025-08-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_reasontopicslist_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='action_client',
            new_name='client',
        ),
        migrations.AddField(
            model_name='actions',
            name='action_reason_code',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='reason_for_action', to='client.reasontopicslist'),
            preserve_default=False,
        ),
    ]
