# Generated by Django 4.2.23 on 2025-08-20 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0009_rename_action_client_actions_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_type', models.CharField(max_length=150, verbose_name='Communication Types')),
            ],
        ),
        migrations.CreateModel(
            name='CoreChallengeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_challenge', models.CharField(max_length=150, verbose_name='Core Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=150, verbose_name='Fund Name')),
                ('fund_active_status', models.BooleanField(default=True, verbose_name='Fund is active')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=150, verbose_name='Entity Name')),
                ('ref_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('ref_contact_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact Name')),
                ('ref_active_status', models.BooleanField(default=True, verbose_name='Entity is active')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Client is active'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Client Middle Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='vet_status',
            field=models.BooleanField(default=False, verbose_name='Client is a veteran'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(verbose_name='Client Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Client First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Client Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_main_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='HOME', max_length=7),
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateField()),
                ('eval_time', models.IntegerField()),
                ('eval_notes', models.TextField()),
                ('eval_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_comm', to='client.communicationslist', verbose_name='Communication Capability')),
                ('eval_core_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_core_challenge', to='client.corechallengelist', verbose_name='Core Challenge')),
                ('eval_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Complete by')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='client.referralentities', verbose_name='Client referred by'),
        ),
    ]
