# Generated by Django 4.2.23 on 2025-08-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_communicationslist_corechallengelist_fundingsources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontacts',
            name='add_contact_phone_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='HOME', max_length=7),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_secondary_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Cell', 'Cell'), ('Office', 'Office'), ('Other', 'Other')], default='CELL', max_length=7),
        ),
    ]
