# Generated by Django 4.2.23 on 2025-08-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_eval_eval_mobility_alter_goal_goal_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDisabilityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=150, verbose_name='Disability Name')),
            ],
        ),
    ]
