# Generated by Django 4.2.23 on 2025-08-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_generaldisabilitylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='disability_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Disability Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='gen_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_disability', to='client.generaldisabilitylist', verbose_name='General Disability'),
        ),
    ]
