# Generated by Django 4.2.23 on 2025-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_eval_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='action_ticket_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_init_by',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Virtual Meeting', 'Virtual Meeting'), ('In Person', 'In Person'), ('Office Visit', 'Office Visit'), ('Email Exchange', 'Email Exchange'), ('Training', 'Training Request'), ('Equipment Issue', 'Equipment Issue'), ('Text Message', 'Text Message'), ('TeamViewer Consult', 'TeamViewer Consult'), ('Hardware / Software Delivered', 'Hardware / Software Delivered'), ('Hardware / Software Pick-Up', 'Hardware / Software Pick-Up')], default='Client', max_length=30),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_outcome',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Requires Follow-Up', 'Requires Follow-Up')], default='Successful', max_length=30),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Caregiver', 'Caregiver'), ('SHARE', 'SHARE'), ('3rd Party', '3rd Party')], default='Phone', max_length=30),
        ),
    ]
