# Generated by Django 4.2.23 on 2025-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_actions_action_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_follow_up_period',
            field=models.CharField(blank=True, choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
