# Generated by Django 4.2.23 on 2025-08-22 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_actions_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_follow_up_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_follow_up_period',
            field=models.CharField(blank=True, choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
