# Generated by Django 4.2.23 on 2025-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_alter_actions_action_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_init_by',
            field=models.CharField(choices=[('Client', 'Client'), ('Caregiver', 'Caregiver'), ('SHARE', 'SHARE'), ('3rd Party', '3rd Party')], default='Client', max_length=30),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Virtual Meeting', 'Virtual Meeting'), ('In Person', 'In Person'), ('Office Visit', 'Office Visit'), ('Email Exchange', 'Email Exchange'), ('Training', 'Training Request'), ('Equipment Issue', 'Equipment Issue'), ('Text Message', 'Text Message'), ('TeamViewer Consult', 'TeamViewer Consult'), ('Hardware / Software Delivered', 'Hardware / Software Delivered'), ('Hardware / Software Pick-Up', 'Hardware / Software Pick-Up')], default='Phone Call', max_length=30),
        ),
    ]
