# Generated by Django 4.2.23 on 2025-08-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0020_alter_actions_action_follow_up_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_slug', models.CharField(max_length=30)),
                ('ticket_create_date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_issue', models.TextField()),
                ('ticket_status', models.CharField(choices=[('Resolved', 'Resolved'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], max_length=30)),
                ('ticket_resolved_date', models.DateField(blank=True, null=True)),
                ('ticket_open', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_for_action', to='client.actions')),
                ('ticket_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('ticket_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_update_date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_update_notes', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_for_ticket', to='client.ticket')),
                ('ticket_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_updates_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
