# Generated by Django 4.2.23 on 2025-08-25 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0021_ticket_ticketupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_assigned_to',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Ticket created by'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_issue',
            field=models.TextField(verbose_name='Issue Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_resolved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Resolved Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_slug',
            field=models.CharField(max_length=30, verbose_name='Ticket Short Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], default='ACTIVE', max_length=30, verbose_name='Ticket Status'),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='ticket_update_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
