# Generated by Django 4.2.23 on 2025-08-25 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0022_remove_ticket_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketupdate',
            name='ticket_assign_to',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assigned_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Assign to'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='ticket_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_updates_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Update by'),
        ),
    ]
