# Generated by Django 4.2.23 on 2025-11-13 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0023_ticketupdate_ticket_assign_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gen_disability',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='gen_disability', to='client.generaldisabilitylist', verbose_name='General Disability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='client.referralentities', verbose_name='Client referred by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eval',
            name='eval_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Evaluation'),
        ),
        migrations.AlterField(
            model_name='eval',
            name='eval_mobility',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Somewhat Limited', 'Somewhat Limited'), ('Severally Limited', 'Severally Limited'), ('Wheelchair', 'Wheelchair'), ('Bedridden', 'Bedridden')], default='NORM', max_length=50, verbose_name='Client Mobility'),
        ),
        migrations.AlterField(
            model_name='eval',
            name='eval_notes',
            field=models.TextField(verbose_name='Evaluation Notes'),
        ),
        migrations.AlterField(
            model_name='eval',
            name='eval_time',
            field=models.IntegerField(verbose_name='Time Spent (in minutes)'),
        ),
        migrations.AlterField(
            model_name='eval',
            name='eval_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Complete By'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_time_spent',
            field=models.IntegerField(verbose_name='Staff Time Spent (in minutes)'),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='g_status_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes about this update'),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='g_status_staff_time',
            field=models.IntegerField(verbose_name='Staff Time Spent (in minutes)'),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='g_status_update',
            field=models.CharField(choices=[('Evaluated', 'Evaluated'), ('Achieved', 'Achieved')], default='EVAL', max_length=30, verbose_name='Goal Status Update'),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='g_update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Update'),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='ticket_update_notes',
            field=models.TextField(default='a note', verbose_name='Ticket Update Notes'),
            preserve_default=False,
        ),
    ]
