# Generated by Django 4.2.23 on 2025-12-17 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentstatus_status_notes_and_more'),
        ('client', '0024_alter_client_gen_disability_alter_client_referred_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_with_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
    ]
