# Generated by Django 4.2.23 on 2025-12-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0025_equipment_with_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='now_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Action'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Custom Date'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_init_by',
            field=models.CharField(choices=[('Client', 'Client'), ('Caregiver', 'Caregiver'), ('SHARE', 'SHARE'), ('3rd Party', '3rd Party')], default='Client', max_length=30, verbose_name='Action Initiated By'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_outcome',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Requires Follow-Up', 'Requires Follow-Up')], default='Successful', max_length=30, verbose_name='What was the outcome?'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Virtual Meeting', 'Virtual Meeting'), ('In Person', 'In Person'), ('Office Visit', 'Office Visit'), ('Email Exchange', 'Email Exchange'), ('Training', 'Training Request'), ('Equipment Issue', 'Equipment Issue'), ('Text Message', 'Text Message'), ('TeamViewer Consult', 'TeamViewer Consult'), ('Hardware / Software Delivered', 'Hardware / Software Delivered'), ('Hardware / Software Pick-Up', 'Hardware / Software Pick-Up')], default='Phone Call', max_length=30, verbose_name='Type of Action'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_by_user', to=settings.AUTH_USER_MODEL, verbose_name='User who performed the action'),
        ),
    ]
