# Generated by Django 4.2.23 on 2025-08-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0007_addcontacts_goal_goalupdate_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_name', models.CharField(max_length=30)),
                ('eq_type', models.CharField(choices=[('System', 'System'), ('Peripheral', 'Peripheral'), ('Interface', 'Interface'), ('Software', 'Software'), ('Other', 'Other')], default='System', max_length=25)),
                ('eq_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('status', models.CharField(choices=[('Inv', 'In Inventory'), ('Client', 'With Client'), ('Return', 'Returned from Client'), ('Maint', 'Maintenance'), ('Sunset', 'Sunset'), ('Lost', 'Lost'), ('RTO', 'Returned to owner'), ('Unknown', 'Unknown')], default='Inv', max_length=25)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_with_clients', to='client.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='equipment.equipment')),
            ],
        ),
    ]
