# Generated by Django 4.2.23 on 2025-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstatus',
            name='status',
            field=models.CharField(choices=[('In Inventory', 'In Inventory'), ('With Client', 'With Client'), ('Returned from Client', 'Returned from Client'), ('Maintenance', 'Maintenance'), ('Sunset', 'Sunset'), ('Lost', 'Lost'), ('Returned to owner', 'Returned to owner'), ('Unknown', 'Unknown')], default='Inv', max_length=25),
        ),
    ]
