# Generated by Django 4.2.23 on 2025-08-20 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_eval_client'),
        ('equipment', '0002_alter_equipmentstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eq_active_status',
            field=models.BooleanField(default=True, verbose_name='Equipment is active'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_client_owner', to='client.client', verbose_name='Client Owner'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Equipment Date Acquired'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_funding_source', to='client.fundingsources', verbose_name='Funding Source'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Equipment Notes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_owner',
            field=models.CharField(choices=[('Client', 'Client'), ('Foundation', 'Foundation'), ('Third Party', 'Third Party')], default='FOUNDATION', max_length=25),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipment Serial / ID Number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_type',
            field=models.CharField(choices=[('System', 'System'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('iPad', 'iPad'), ('Cell Phone', 'Cell Phone'), ('Eye Gaze', 'Eye Gaze'), ('Software-Dragon', 'Software-Dragon'), ('Software-Tobii', 'Software-Tobii'), ('Software-Vision', 'Software-Vision'), ('Software-Other', 'Software-Other'), ('Peripheral', 'Peripheral'), ('Interface', 'Interface'), ('Software', 'Software'), ('Other', 'Other')], default='System', max_length=25),
        ),
    ]
