# Generated by Django 4.2.23 on 2025-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_eq_active_status_equipment_eq_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_name',
            field=models.CharField(max_length=30, verbose_name='Equipment Name or Slug'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_owner',
            field=models.CharField(choices=[('Client', 'Client'), ('Foundation', 'Foundation'), ('Third Party', 'Third Party')], default='Foundation', max_length=25, verbose_name='Equipment Owner'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_type',
            field=models.CharField(choices=[('System', 'System'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('iPad', 'iPad'), ('Cell Phone', 'Cell Phone'), ('Eye Gaze', 'Eye Gaze'), ('Software-Dragon', 'Software-Dragon'), ('Software-Tobii', 'Software-Tobii'), ('Software-Vision', 'Software-Vision'), ('Software-Other', 'Software-Other'), ('Peripheral', 'Peripheral'), ('Interface', 'Interface'), ('Software', 'Software'), ('Other', 'Other')], default='System', max_length=25, verbose_name='Equipment Type'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Equipment Value'),
        ),
        migrations.AlterField(
            model_name='equipmentstatus',
            name='status',
            field=models.CharField(choices=[('INV', 'In Inventory'), ('CLIENT', 'With Client'), ('RETURN', 'Returned from Client'), ('MAINT', 'Maintenance'), ('SUNSET', 'Sunset'), ('LOST', 'Lost'), ('RTO', 'Returned to owner'), ('UNKNOWN', 'Unknown')], default='Inv', max_length=25),
        ),
    ]
