# Generated by Django 4.2.23 on 2025-11-13 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_eq_name_alter_equipment_eq_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentstatus',
            name='status_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Update Notes'),
        ),
        migrations.AlterField(
            model_name='equipmentstatus',
            name='status_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
